### ISSUE TITLE
TypeError: Document not active on exitFullscreen

### ISSUE THREAD

**Issue by ameensom** [jpilfold/ngx-image-viewer#23] opened 2018-10-09 08:36 UTC
Hello

I've been getting this error on loading the component, it is releated to screenfull.js

Browser Report :

```
Uncaught (in promise) TypeError: Document not active
    at exit (requests-new-requests-new-module-ngfactory~requests-old-requests-old-module-ngfactory.c31c04ce286bdb4bfcb7.js:formatted:258)
    at n.ngOnChanges (requests-new-requests-new-module-ngfactory~requests-old-requests-old-module-ngfactory.c31c04ce286bdb4bfcb7.js:formatted:490)
    at vendor.cca2f135bd1b8e11a575.js:1
    at vendor.cca2f135bd1b8e11a575.js:1
    at $s (vendor.cca2f135bd1b8e11a575.js:1)
    at Ea (vendor.cca2f135bd1b8e11a575.js:1)
    at Object.updateDirectives (requests-new-requests-new-module-ngfactory~requests-old-requests-old-module-ngfactory.c31c04ce286bdb4bfcb7.js:formatted:215)
    at Object.updateDirectives (vendor.cca2f135bd1b8e11a575.js:1)
    at Zs (vendor.cca2f135bd1b8e11a575.js:1)
    at ia (vendor.cca2f135bd1b8e11a575.js:1)
    at na (vendor.cca2f135bd1b8e11a575.js:1)
    at Zs (vendor.cca2f135bd1b8e11a575.js:1)
    at ia (vendor.cca2f135bd1b8e11a575.js:1)
    at ra (vendor.cca2f135bd1b8e11a575.js:1)
    at Zs (vendor.cca2f135bd1b8e11a575.js:1)
    at ia (vendor.cca2f135bd1b8e11a575.js:1)
    at ra (vendor.cca2f135bd1b8e11a575.js:1)
    at Zs (vendor.cca2f135bd1b8e11a575.js:1)
    at ia (vendor.cca2f135bd1b8e11a575.js:1)
    at na (vendor.cca2f135bd1b8e11a575.js:1)
    at Zs (vendor.cca2f135bd1b8e11a575.js:1)
    at ia (vendor.cca2f135bd1b8e11a575.js:1)
    at ra (vendor.cca2f135bd1b8e11a575.js:1)
    at Zs (vendor.cca2f135bd1b8e11a575.js:1)
    at ia (vendor.cca2f135bd1b8e11a575.js:1)
    at ra (vendor.cca2f135bd1b8e11a575.js:1)
    at Zs (vendor.cca2f135bd1b8e11a575.js:1)
    at ia (vendor.cca2f135bd1b8e11a575.js:1)
    at na (vendor.cca2f135bd1b8e11a575.js:1)
    at Zs (vendor.cca2f135bd1b8e11a575.js:1)
    at ia (vendor.cca2f135bd1b8e11a575.js:1)
    at ra (vendor.cca2f135bd1b8e11a575.js:1)
    at Zs (vendor.cca2f135bd1b8e11a575.js:1)
    at ia (vendor.cca2f135bd1b8e11a575.js:1)
    at na (vendor.cca2f135bd1b8e11a575.js:1)
    at Zs (vendor.cca2f135bd1b8e11a575.js:1)
    at ia (vendor.cca2f135bd1b8e11a575.js:1)
    at ra (vendor.cca2f135bd1b8e11a575.js:1)
    at Zs (vendor.cca2f135bd1b8e11a575.js:1)
    at ia (vendor.cca2f135bd1b8e11a575.js:1)
    at na (vendor.cca2f135bd1b8e11a575.js:1)
    at Zs (vendor.cca2f135bd1b8e11a575.js:1)
    at ia (vendor.cca2f135bd1b8e11a575.js:1)
    at ra (vendor.cca2f135bd1b8e11a575.js:1)
    at Zs (vendor.cca2f135bd1b8e11a575.js:1)
    at ia (vendor.cca2f135bd1b8e11a575.js:1)
    at na (vendor.cca2f135bd1b8e11a575.js:1)
    at Zs (vendor.cca2f135bd1b8e11a575.js:1)
    at ia (vendor.cca2f135bd1b8e11a575.js:1)
    at ra (vendor.cca2f135bd1b8e11a575.js:1)
```

Sentry highlighted the following line 

`./node_modules/screenfull/dist/screenfull.js.pre-build-optimizer.js`

```
	} else {
				elem[request](keyboardAllowed && Element.ALLOW_KEYBOARD_INPUT);
			}
		},
		exit: function () {
			document[fn.exitFullscreen]();
		},
		toggle: function (elem) {
			if (this.isFullscreen) {
				this.exit();
			} else {
```

**Comment by jpilfold** [comment] 2018-10-09 08:39
Are you able to create a Stackblitz or something that reproduces the issue please?

**Comment by ameensom** [comment] 2018-10-09 08:58
I don't think that's possible

**Comment by jpilfold** [comment] 2018-10-09 09:03
@ameensom It will be incredibly difficult to fix this issue if I'm not able to reproduce it

**Comment by jpilfold** [comment] 2018-10-10 02:32
@ameensom Do you have a repository I can clone that exhibits this behaviour? If not, can you at least give me the steps necessary to reproduce this issue? Without, I will need to close this issue.

**Closed** 2018-11-10 13:36 UTC

**Comment by diegocr** [comment] 2018-12-05 19:33
Googling for `TypeError: Document not active` gives only **one** result, this repo's ticket/issue - awesome SEO opportunity! ;-)

Seriously, as of Chrome 71, it looks like that exception is thrown when invoking `document.exitFullscreen()` while **not** in full-screen mode, so the fix is quite obvious :)

**Comment by wendyjw** [comment] 2018-12-11 04:00
I also encountered this problem in Chrome 71

**Comment by xristostz** [comment] 2018-12-12 08:37
I had the same issue since the last Chrome update to 71.
In case this is helpful, this is the error when loading the component:
`screenfull.js:102 Uncaught (in promise) TypeError: Document not active
    at exit (screenfull.js:102)
    at ToggleFullscreenDirective.ngOnChanges (ngx-image-viewer.es5.js:289)
    at checkAndUpdateDirectiveInline (core.js:12093)
    at checkAndUpdateNodeInline (core.js:13599)
    at checkAndUpdateNode (core.js:13542)
    at debugCheckAndUpdateNode (core.js:14414)
    at debugCheckDirectivesFn (core.js:14355)
    at Object.eval [as updateDirectives] (ImageViewerComponent.html:2)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:14340)
    at checkAndUpdateView (core.js:13509)`

**Comment by shrijoshi24** [comment] 2018-12-12 14:53
I am seeing this document.exitFullscreen() error as well on Chrome 71. Didn't happen on the previous versions. Is there a fix for this or we expect it to be fixed with next version of Chrome?

**Comment by gerald-odonnell7** [comment] 2018-12-13 09:25
SOLUTION:

Go into lg-fullscreen.min.js and surround:

{document.exitFullscreen?document.exitFullscreen():document.msExitFullscreen?document.msExitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitExitFullscreen&&document.webkitExitFullscreen()}

with:

{(window.fullScreen) ? document.exitFullscreen?document.exitFullscreen():document.msExitFullscreen?document.msExitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitExitFullscreen&&document.webkitExitFullscreen() : ''}

where you are adding (window.fullScreen) ? in front of the given code and then put a colon and two apostrophes after (that is not a quote but two apostrophes).

**Comment by turnono** [comment] 2018-12-19 21:44
This seems to fix it:

exit: function() {
      if (document.fullscreen) {
        document[fn.exitFullscreen]();
      }
    },

**Comment by turnono** [comment] 2018-12-19 21:45
This seems to fix it:
`exit: function() {
if (document.fullscreen) {
documentfn.exitFullscreen;
}
},`

**Comment by artf** [comment] 2018-12-19 23:24
[`document.fullscreen`](https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreen) is deprecated, instead you should use the [`document.fullscreenElement`](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/fullscreenElement) with vendor prefixes
```js
if (document.fullscreenElement || 
	document.webkitFullscreenElement || 
	document.mozFullScreenElement) {
	// can use exitFullscreen
}
```

**Comment by ManyRouc** [comment] 2019-01-04 19:33
Hi there,

I juste encountred the same issue with screenfull, here is my solution that fixed this :+1: 

1. Go to the file : ~src/node_modules/screenfull/dist/screenfull.js 

2. find around line 100 the exit function 

3.replace with the following : 
 
```
		exit: function () {
			if (this.isFullscreen) {
				document[fn.exitFullscreen]();
			}
		},
```

Cheers

**Comment by sachinchoolur** [comment] 2019-02-19 03:57
The issue has been fixed in the original lightGallery. Thanks for pointing this out

**Comment by krakapuzlis** [comment] 2019-02-20 15:35
So what have you guys done with this problem? How you manage to get rid of it?

**Comment by MsumanP** [comment] 2019-03-12 09:13
I am still getting same error.

**Comment by BH-GeGe** [comment] 2019-03-20 03:21
> [`document.fullscreen`](https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreen) is deprecated, instead you should use the [`document.fullscreenElement`](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/fullscreenElement) with vendor prefixes
> 
> ```js
> if (document.fullscreenElement || 
> 	document.webkitFullscreenElement || 
> 	document.mozFullScreenElement) {
> 	// can use exitFullscreen
> }
> ```

This solution has been solved.👍

**Comment by l1nknyto** [comment] 2019-04-05 11:51
The error is also happened when my application starting.

> Uncaught (in promise) TypeError: Document not active
>     at Object.exit (screenfull.js:102)
>     at ToggleFullscreenDirective.ngOnChanges (fullscreen.directive.ts:18)

I see this error too on demo page ( https://angular-2wrbwp.stackblitz.io/ )

I eliminate it by checking variable changes, skip if this is the first change.
Working so far, but i don't know the side effect.

```
export class ToggleFullscreenDirective implements OnChanges {
...
    ngOnChanges(changes: SimpleChanges) {
        if (!changes.isFullscreen.isFirstChange()) {
          if (this.isFullscreen && screenfull.enabled) {
            screenfull.request(this.el.nativeElement);
          } else if (screenfull.enabled) {
            screenfull.exit();
          }
        }
    }
}

```

**Comment by muscaiu** [comment] 2019-11-29 14:35
I'm having a similar issue: https://stackoverflow.com/questions/59106462/document-is-not-active

**Comment by Shriraam-Ramesh** [comment] 2020-03-18 05:22
Use this,
  var elem = document.documentElement;
           if (elem.mozRequestFullScreen) {
            elem.mozRequestFullScreen();
          } else if (elem.webkitRequestFullscreen) {
            elem.webkitRequestFullscreen();
          } else if (elem.msRequestFullscreen) {
            elem.msRequestFullscreen();
          }
for opening full screen and this,

if (document.mozCancelFullScreen) {
              document.mozCancelFullScreen();
            } else if (document.webkitExitFullscreen) {
              document.webkitExitFullscreen();
            } else if (document.msExitFullscreen) {
              document.msExitFullscreen();
            }
for closing full screen.

Hope this helps.  @ameensom

**Comment by txwizard** [comment] 2020-12-30 22:02
How do you respond when the exception is raised in a package, such as [https://github.com/jplayer/jPlayer](url)? Would it help in this case to register a listener? For now, I'm not going to worry too much, since the full screen mode exits as expected.

**Comment by CodeOutput** [comment] 2021-06-09 15:41
> This seems to fix it:
> `exit: function() { if (document.fullscreen) { documentfn.exitFullscreen; } },`

`exit: function() { if (document.fullscreen) { document[fn.exitFullscreen](); } } is working`

**Comment by Mostafa-Fathi** [comment] 2023-02-09 09:41
> > This seems to fix it:
> > `exit: function() { if (document.fullscreen) { documentfn.exitFullscreen; } },`
> 
> `exit: function() { if (document.fullscreen) { document[fn.exitFullscreen](); } } is working`

so where i should use this lines ?
